baseURL = "https://hugo-site-project.netlify.app"
languageCode = "ar-ar"
title = "Curto Circuito"
theme = "hugo-theme-project"

DefaultContentLanguage = "ar-ar"

paginate = 10
paginatePath = "pagina"
disableKinds = ["section", "taxonomyTerm"]
removePathAccents = true

[outputFormats.SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isHTML = true
    noUgly = true
    rel = "sitemap"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"


[permalinks]
    posts = "/:year/:month/:day/:slug/"
    pages = "/:slug/"
    authors = "/autor/:slug/"
    categories = "/:slug/"
    tags = "/tudo-sobre/:slug/"
