# Meta Data for SEO

## Homepage
title = "بيتبريس"
titleSeparator = "|"
titleAddition = "Filmes, Séries, Animes, Games, Tecnologia"
description = "bitpresse هي خدمة مجانية تساعدك على تعلم blockchain و bitcoin والتسويق والتشفير والاقتصاد والتجارة وغير ذلك."

## Open Graph
images = ["doks.png"]
ogLocale = "ar_AR"
domainTLD = "bitpresse.netlify.app"
titleHome = "بيتبريس"

## Twitter Cards
twitterSite = "@cryptoserie"
twitterCreator = "@cryptoserie"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "بيتبريس"
schemaAuthor = "بيتبريس"
schemaAuthorTwitter = "https://twitter.com/cryptoserie"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/bitpresse/"
schemaAuthorGitHub = "https://github.com/bitpresse"
schemaLocale = "ar-AR"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/cryptoserie"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/bitpresse"
schemaSection = "blog"

## Chrome Browser
themeColor = "#fff"

# Social
twitter = "cryptoserie"
instagram = "cryptoserie"
