baseURL = "https://hugo-site-project.netlify.app"
languageCode = "pt-br"
title = "Curto Circuito"
theme = "hugo-theme-project"

DefaultContentLanguage = "pt-br"

paginate = 10
paginatePath = "pagina"
disableKinds = ["section", "taxonomyTerm"]
removePathAccents = true

[outputFormats.SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isHTML = true
    noUgly = true
    rel = "sitemap"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"


[permalinks]
    posts = '/:year/:month/:day/:slug/'
    pages = '/:slug/'
    authors = '/autor/:slug/'
    categories = '/:slug/'
    tags = '/tudo-sobre/:slug/'

[params]
    ## Site
    siteTitle = "Curto Circuito"
    siteTitleSeparator = "|"
    siteTitleAppend = "Filmes, Séries, Animes, Games, Tecnologia"
    siteDescription = "Notícias, reportagens e mais sobre filmes, séries, animes, mangás, games, tecnologia, HQs, livros, cosplays e tudo mais sobre o universo nerd!"

    ## Open Graph
    images = ['uploads/cubo-atômico.webp']
    ogLocale = 'pt_BR'
    domainTLD = 'cuboatomicoexperimental.netlify.app'
    siteURL = 'https://cuboatomicoexperimental.netlify.app'
    titleHome = 'Cubo Atômico'

    ## Twitter Cards
    twitterSite = '@henriquepicanco'

    ## Chrome Browser
    themeColor = "#f60"

    ## Social Navigation
    twitter = 'https://twitter.com/henriquepicanco/'
    instagram = 'https://www.instagram.com/henriquepicanco97/'

[menu]
    [[menu.main]]
    identifier = 'filmes'
    name = 'Filmes'
    url = '/filmes/'
    weight = 1

    [[menu.main]]
    identifier = 'series-e-tv'
    name = 'Séries e TV'
    url = '/series-e-tv/'
    weight = 2

    [[menu.main]]
    identifier = 'animes-e-mangas'
    name = 'Animes e Mangás'
    url = '/animes-e-mangas/'
    weight = 3

    [[menu.main]]
    identifier = 'games'
    name = 'Games'
    url = '/games/'
    weight = 4

    [[menu.main]]
    identifier = 'tecnologia'
    name = 'Tecnologia'
    url = '/tecnologia/'
    weight = 5

    [[menu.footer]]
    name = 'Sobre'
    url = '/sobre'
    weight = 1

    [[menu.footer]]
    name = 'Política de Privacidade'
    url = '/politica-de-privacidade'
    weight = 2

    [[menu.footer]]
    name = 'Contato'
    url = '/contato'
    weight = 3
